name: Deploy a Producció

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.SSH_USERNAME }}
          server-ip: ${{ secrets.SSH_HOST }}
          remote-path: ${{ secrets.TARGET_PATH }}
          local-path: .
