name: Deploy a Producció

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # La clau privada SSH
          REMOTE_USER: ${{ secrets.REMOTE_USER }}         # Usuari SSH
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}         # IP o domini del servidor
          TARGET: ${{ secrets.TARGET }}                   # Ruta al servidor
          SOURCE: '.'                                     # Directori local a desplegar
