name: Deploy a Producció

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        TARGET: '/web/a23josnincal.daw.inspedralbes.cat/public_html'  # Aquesta és la ruta correcta
        SOURCE: .

